/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Operation */

#ifndef _Included_Operation
#define _Included_Operation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Operation
 * Method:    greet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Operation_greet
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
